language: java
jdk:
  - openjdk11

branches:
  only:
    - develop

#Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew clean build -x test"

before_deploy:
  - zip -r jiok-service *
  - mkdir -p deploy
  - mv jiok-service.zip deploy/jiok-service.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: jiok-service-s3
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: develop

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - hyunjiok10@gmail.com
      - lje911@gmail.com



