language: java
jdk:
  - openjdk11

branches:
  only:
    - develop

#Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew clean build -x test"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*SNAPSHOT.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/jiok-service.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: jiok-service-s3
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: develop

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: jiok-service-s3
    key: jiok-service.zip
    bundle_type: zip
    application: jiok-service-deploy-application
    deployment_group: jiok-service-deploy-application-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      branch: develop

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - hyunjiok10@gmail.com
      - lje911@gmail.com



