version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/jiok-service/Purchase/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 555

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user